### ISSUE TITLE
v0.4: Type-safe, Native BEAM Binaries

### ISSUE THREAD

**Issue by ostera** [AbstractMachinesLab/zap#3]
## Summary

Crane v0.4 should include the minimum goals, rules, and toolchains necessary to put together type-safe dependency-free BEAM projects that can execute as native binaries.

We'll defer to future releases the following features:
* Support for Clojerl, Elixir, Gleam, etc
* Rules for OTP releases, cram, eunit, ct, and proper tests
* Rules for building docker images

## Checklist 

These are intentionally capped checklists to keep high-level visibility of the work that needs to be done to get to v0.4.

#### Goals

- [ ] Can create a new project (`crane new --path . my_workspace`)
- [x] Can build and run project targets (`crane build //....` and `crane run //...`)
- [x] Can clean a workspace (`crane clean`)
- [ ] Can copy outputs out of the workspace (`crane copy-outputs //... [--target_dir=./outputs]`)

#### Rules

- [x] `erlang_library` -- to build Erlang sources
- [ ] `otp_application` -- to build OTP compliant applications
- [x] `caramel_library` -- to build OCaml sources
- [x] `beam_archive` -- to package libraries and applications together
- [ ] `lam_binary` -- to create native Erlang binaries

#### Hermeticity

- [ ] All toolchains depend and use the managed Erlang toolchain
- [ ] Downloads do not depend on an externall installed `wget` or `curl`
- [ ] Archiving / unarchiving does not depend on externally installed `tar` nor `gzip`

#### Toolchains

- [ ] Can be installed from source:
  - [ ] Erlang
- [ ] Can be installed from binary release:
  - [ ] Erlang
  - [x] Caramel
  - [ ] LAM
 
#### Examples

- [ ] Small CLI that runs as binaries:
  - [ ] `tree`
  - [ ] `http-get`

**Comment by ostera** [comment]
The scope has changed here, and this tracking issue doesn't make sense anymore.
