### ISSUE TITLE
Crane Feature & Rules Status

### ISSUE THREAD

**Issue by ostera** [AbstractMachinesLab/zap#4]
Just like for LAM I opened [some](https://github.com/AbstractMachinesLab/lam/issues/6) [tracking](https://github.com/AbstractMachinesLab/lam/issues/5) [issues](https://github.com/AbstractMachinesLab/lam/issues/4), here's one for Crane features and rules.

### Goals

Goals are things Crane can do with your project.

- [x] `crane clean`: clean a project
- [x] `crane build [target]`: incrementally build a target and its dependencies
- [x] `crane run [target]`: incrementally build a target and its dependencies, then run it
- [ ] `crane query`: find targets in the build graph
- [ ] `crane deps`: fetch, verify, and build dependencies
- [ ] `crane new`: bootstrap new projects
- [ ] `crane test`: run tests and support output promotion for snapshots
- [ ] `crane lift`: wrap rebar3/erlang.mk/mix projects
- [ ] `crane fmt`: format all sources

### Hermeticity & Correctness

- [x] manage a sandboxed build environment  
- [ ] pack every utility needed to not rely on global tools
- [ ] use a build.lock file to prevent local concurrent execution

## Rules

Rules are the specific actions that Crane can take when building your project.

#### Language Support

- [x] `caramel_library`
- [x] `clojerl_library`
- [ ] `clojerl_shell`
- [x] `elixir_library`
- [ ] `elixir_shell`
- [x] `erlang_library`
- [x] `erlang_shell`
- [x] `gleam_library`

#### OTP

- [x] `beam_archive`
- [ ] `beam_release`
- [ ] `otp_application`
- [ ] `otp_release`

#### Tests

- [ ] `ct_test`
- [ ] `eunit_test`
- [ ] `exunit_test`
- [ ] `proper_test`
- [ ] `snapshot_test`

#### Releases
- [ ] `lam_native_binary`
- [ ] `lam_wasm_binary`
- [ ] `lam_web_binary`
- [ ] `lumen_binary`
- [ ] `beam_image`: a lightweight container image with an OTP/ERTS release

#### Utility / Workflow
- [ ] `image_push`: push an image to a DockerHub

**Comment by ostera** [comment]
This is no longer relevant since the Zap model has pushed all of the rules out of the core.
